package fr.uge.utilities;

import java.util.Objects;

/**
 * The HistoryDTO record is used to represent the data transfer object for storing the history of a code analysis.
 * It holds the details of the class, its associated responses, and additional metadata.
 */
public record HistoryDTO(String classText, String llmResponse, String compilerResponse, String history,
                         String timestamp, boolean success) {

  /**
   * Constructor that validates all fields to ensure they are not null.
   *
   * @param classText      The class source code.
   * @param llmResponse    The response generated by the LLM (Language Learning Model).
   * @param compilerResponse The response generated by the compiler.
   * @param history        The history of the analysis.
   * @param timestamp      The timestamp of when the entry was created.
   * @param success        A flag indicating whether the compiler analysis was successful.
   */
  public HistoryDTO {
    Objects.requireNonNull(classText, "classText must not be null");
    Objects.requireNonNull(llmResponse, "llmResponse must not be null");
    Objects.requireNonNull(compilerResponse, "compilerResponse must not be null");
    Objects.requireNonNull(history, "history must not be null");
    Objects.requireNonNull(timestamp, "timestamp must not be null");
  }
}
