package fr.uge.utilities;

import java.util.Objects;

/**
 * The ResponseBoxer record is used to encapsulate the responses and associated data for a code analysis.
 * It stores the content description, the class text, and responses from both the compiler and the LLM,
 * along with a flag indicating the success of the operation.
 */
public record ResponseBoxer(String contentDescription, String classText, String compilerResponse, String llmResponse, boolean success) {

  /**
   * Constructor that validates all fields to ensure they are not null.
   *
   * @param contentDescription A description of the content or response.
   * @param classText          The source code of the class being analyzed.
   * @param compilerResponse   The response generated by the compiler.
   * @param llmResponse        The response generated by the Language Learning Model (LLM).
   * @param success            A flag indicating whether the operation was successful.
   */
  public ResponseBoxer {
    Objects.requireNonNull(contentDescription, "contentDescription must not be null");
    Objects.requireNonNull(classText, "classText must not be null");
    Objects.requireNonNull(compilerResponse, "compilerResponse must not be null");
    Objects.requireNonNull(llmResponse, "llmResponse must not be null");
  }
}
